class LoginEntity {
	dynamic fetchCard;
	dynamic creationTime;
	dynamic inviteNumber;
	dynamic loginPhone;
	dynamic agentId;
	dynamic shopBalance;
	dynamic typeUser;
	String userName;
	dynamic downUrl;
	String mobileState;
	dynamic typeNumber;
	dynamic managePassword;
	dynamic userGrade;
	dynamic picName;
	dynamic payMoney;
	dynamic agencyBalance;
	dynamic secretKey;
	dynamic brandNumber;
	dynamic gradeId;
	dynamic payPassword;
	dynamic sealState;
	String mobileData;
	dynamic idNumber;
	dynamic mobileCode;
	String agreement;
	dynamic typeId;
	dynamic walletBalance;
	dynamic brandId;
	int superiorId;
	dynamic registerType;
	int userId;
	dynamic clientPassword;
	dynamic inviteBalance;

	LoginEntity({this.fetchCard, this.creationTime, this.inviteNumber, this.loginPhone, this.agentId, this.shopBalance, this.typeUser, this.userName, this.downUrl, this.mobileState, this.typeNumber, this.managePassword, this.userGrade, this.picName, this.payMoney, this.agencyBalance, this.secretKey, this.brandNumber, this.gradeId, this.payPassword, this.sealState, this.mobileData, this.idNumber, this.mobileCode, this.agreement, this.typeId, this.walletBalance, this.brandId, this.superiorId, this.registerType, this.userId, this.clientPassword, this.inviteBalance});

	LoginEntity.fromJson(Map<String, dynamic> json) {
		fetchCard = json['fetch_card'];
		creationTime = json['creation_time'];
		inviteNumber = json['invite_number'];
		loginPhone = json['login_phone'];
		agentId = json['agent_id'];
		shopBalance = json['shop_balance'];
		typeUser = json['type_user'];
		userName = json['user_name'];
		downUrl = json['down_url'];
		mobileState = json['mobileState'];
		typeNumber = json['type_number'];
		managePassword = json['manage_password'];
		userGrade = json['user_grade'];
		picName = json['picName'];
		payMoney = json['pay_money'];
		agencyBalance = json['agency_balance'];
		secretKey = json['secret_key'];
		brandNumber = json['brand_number'];
		gradeId = json['grade_id'];
		payPassword = json['pay_password'];
		sealState = json['seal_state'];
		mobileData = json['mobileData'];
		idNumber = json['id_number'];
		mobileCode = json['mobileCode'];
		agreement = json['agreement'];
		typeId = json['type_id'];
		walletBalance = json['wallet_balance'];
		brandId = json['brand_id'];
		superiorId = json['superior_id'];
		registerType = json['register_type'];
		userId = json['user_id'];
		clientPassword = json['client_password'];
		inviteBalance = json['invite_balance'];
	}

	Map<String, dynamic> toJson() {
		final Map<String, dynamic> data = new Map<String, dynamic>();
		data['fetch_card'] = this.fetchCard;
		data['creation_time'] = this.creationTime;
		data['invite_number'] = this.inviteNumber;
		data['login_phone'] = this.loginPhone;
		data['agent_id'] = this.agentId;
		data['shop_balance'] = this.shopBalance;
		data['type_user'] = this.typeUser;
		data['user_name'] = this.userName;
		data['down_url'] = this.downUrl;
		data['mobileState'] = this.mobileState;
		data['type_number'] = this.typeNumber;
		data['manage_password'] = this.managePassword;
		data['user_grade'] = this.userGrade;
		data['picName'] = this.picName;
		data['pay_money'] = this.payMoney;
		data['agency_balance'] = this.agencyBalance;
		data['secret_key'] = this.secretKey;
		data['brand_number'] = this.brandNumber;
		data['grade_id'] = this.gradeId;
		data['pay_password'] = this.payPassword;
		data['seal_state'] = this.sealState;
		data['mobileData'] = this.mobileData;
		data['id_number'] = this.idNumber;
		data['mobileCode'] = this.mobileCode;
		data['agreement'] = this.agreement;
		data['type_id'] = this.typeId;
		data['wallet_balance'] = this.walletBalance;
		data['brand_id'] = this.brandId;
		data['superior_id'] = this.superiorId;
		data['register_type'] = this.registerType;
		data['user_id'] = this.userId;
		data['client_password'] = this.clientPassword;
		data['invite_balance'] = this.inviteBalance;
		return data;
	}
}
